import Foundation

struct CapturedClipboardContent: Equatable {
    let kind: ClipboardEntryKind
    let plainText: String
    let rtfData: Data?
    let pngData: Data?
    let contentHash: String
}

struct PasteboardCaptureLogic {
    private let markerTypeIdentifiers: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    func capture(snapshot: PasteboardSnapshot) -> CapturedClipboardContent? {
        guard snapshot.items.isEmpty == false else { return nil }

        if snapshot.items.contains(where: { item in item.typeIdentifiers.contains(where: markerTypeIdentifiers.contains) }) {
            return nil
        }

        if let item = snapshot.items.first(where: { $0.pngData != nil || $0.tiffData != nil }) {
            if let png = item.pngData {
                return CapturedClipboardContent(
                    kind: .image,
                    plainText: "图片",
                    rtfData: nil,
                    pngData: png,
                    contentHash: ContentHash.sha256Hex(png)
                )
            }
            // TIFF->PNG 在下一步补齐
        }

        if let item = snapshot.items.first(where: { $0.rtfData != nil }), let rtf = item.rtfData {
            return CapturedClipboardContent(
                kind: .rtf,
                plainText: item.string?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "",
                rtfData: rtf,
                pngData: nil,
                contentHash: ContentHash.sha256Hex(rtf)
            )
        }

        let strings = snapshot.items
            .compactMap(\.string)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        guard strings.isEmpty == false else { return nil }

        let joined = strings.joined(separator: "\n")
        let hash = ContentHash.sha256Hex(Data(joined.utf8))
        return CapturedClipboardContent(kind: .text, plainText: joined, rtfData: nil, pngData: nil, contentHash: hash)
    }
}

