name: codespec-workflow
version: 1
description: "codespec workflow on top of OpenSpec (proposal/specs/design/detailed tasks)"

artifacts:
  - id: proposal
    generates: proposal.md
    description: Requirements & intent (why/what/capabilities)
    template: proposal.md
    instruction: |
      Create the proposal artifact for this change.
      Keep the section headers exactly as in the template.
      Write content in Chinese, but keep identifiers/paths/commands/logs as-is.
    requires: []

  - id: specs
    generates: specs/**/*.md
    description: Delta specs (requirements + scenarios)
    template: specs.md
    instruction: |
      Create delta specs that define WHAT changes.
      Requirements MUST use SHALL/MUST.
      Each requirement MUST have at least one scenario.
      Scenarios MUST use exactly `#### Scenario:` (four #).
    requires: [proposal]

  - id: design
    generates: design.md
    description: Technical design (decisions, trade-offs, risks)
    template: design.md
    instruction: |
      Create the design artifact that explains HOW to implement.
      Focus on key decisions, alternatives, and risks.
    requires: [proposal, specs]

  - id: tasks
    generates: tasks.md
    description: Detailed implementation plan (TDD-first)
    template: tasks.md
    instruction: |
      Create a detailed implementation plan in tasks.md.
      Every behavior change MUST have explicit TDD steps: RED → VERIFY_RED → GREEN → VERIFY_GREEN → REFACTOR.
      Use checkboxes `- [ ]` for trackable progress.
    requires: [specs, design]

apply:
  requires: [tasks]
  tracks: tasks.md
